notARepository: "skip"

gui:
  nerdFontsVersion: "3"
  theme:
    defaultFgColor:
      - "#f2f4f8"
    cherryPickedCommitFgColor:
      - "#8cb6ff"
    cherryPickedCommitBgColor:
      - "#33b1ff"
    activeBorderColor:
      - "#ee5396"
      - "bold"
    unstagedChangesColor:
      - "#ee5396"
    selectedLineBgColor:
      - "#181818"
    searchingActiveBorderColor:
      - "#ee5396"
      - "bold"
    optionsTextColor:
      - "#8cb6ff"
    inactiveBorderColor:
      - "#7b7c7e"
  showIcons: true

git:
  pagers:
    - pager: delta --dark --paging=never
      colorArg: always

os:
  open: 'neovide {{filename}}'
  editAtLine: "neovide {{filename}} +{{line}}"

keybinding:
  universal:
    goInto: "o"
    openFile: "<enter>"
    prevBlock: <c-k>
    nextBlock: <c-j>
